In [1]:
import numpy as np
import random
import sys

In [2]:
print(np.__version__) #python -m ipykernel install --user --name=myenv


1.26.4


In [3]:
#Create a 1D array of numbers from 0 to 9
arr_1d = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Create a 1D array of numbers from 0 to 9 using arange() function
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#3. How to create a boolean array?
arr=np.ones((3,3),dtype='bool')
print("Boolean Array:", arr)

Boolean Array: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
#4. How to extract items that satisfy a given condition from 1D array?
print(arr1d[arr1d%2==1])

[1 3 5 7 9]


In [7]:
#5. How to replace items that satisfy a condition with another value in numpy array?
arr1d[arr1d%2==1]=-1
print(arr1d)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
#6. How to replace items that satisfy a condition without affecting the original array?
arr1d=np.arange(10)
out= np.where(arr1d%2==0, arr1d, -1)
print(out)
print(arr1d)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
#7. How to reshape an array?
arr1d.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
#How to stack two arrays vertically?
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,-1)

#method-1:(concatenation)
new_arr=np.concatenate((a,b),axis=0)
print(new_arr)
#method-2: vstack
print(np.vstack((a,b)))
#method-3
np.r_[a, b]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
#9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,-1)

#method-1:(concatenation)
new_arr=np.concatenate((a,b),axis=1)
print(new_arr)
#method-2: vstack
print(np.hstack((a,b)))
#method-3
np.c_[a, b]

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [12]:
#10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])
#each element repeat
ele_repeat=np.repeat(a,3)
#total array repeat
t_repeat=np.tile(a,3)
np.r_[ele_repeat,t_repeat]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [13]:
#11. How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b) #need to flatten if using multidimension array to 1d


array([2, 4])

In [14]:
#12. How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [15]:
#13. How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [16]:
#14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
#method-1
print(a[(a>=5) & (a<=10)])
#method-2
index= np.where((a>=5)&(a<=10))
print(a[index])
#method-3
index=np.where(np.logical_and(a>=5,a<=10))
print(a[index])

[ 6  9 10]
[ 6  9 10]
[ 6  9 10]


In [17]:
#15. How to make a python function that handles scalars to work on numpy arrays?
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
pair_max=np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [18]:
#16. How to swap two columns in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
print(arr)
#Swap columns 1 and 2 in the array arr
print(arr[:,[1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [19]:
#17. How to swap two rows in a 2d numpy array?
#Swap row 1 and 2 in the array arr
print(arr[[1,0,2],:])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [20]:
#18. How to reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)
arr[:: -1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [21]:
#18. How to reverse the rows of a 2D array?
arr[:, :: -1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [22]:
#20. How to create a 2D array containing random floats between 5 and 10?
#method-1
print(np.random.randint(5,10, size=(3,3))+np.random.random((3,3)))

#method-2:
print(np.random.uniform(5,10,size=(3,3)))


[[5.69454639 6.95119307 9.12513125]
 [7.84927493 5.79121118 6.84270317]
 [7.17229266 5.46009682 8.49948898]]
[[6.43284101 7.84948731 6.22622163]
 [6.90420199 9.75128468 7.34449356]
 [6.15526365 9.54043822 5.12098131]]


In [23]:
x=np.random.uniform(5,10,size=(5,3))
np.set_printoptions(precision=3)
print(x[:])

[[7.203 8.119 5.33 ]
 [7.523 8.334 9.355]
 [9.461 8.471 5.645]
 [9.35  5.077 8.164]
 [9.54  7.483 9.428]]


In [24]:
#22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

np.set_printoptions(suppress=True, precision=6)
print(rand_arr)


[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [25]:
#23. How to limit the number of items printed in output of numpy array?
a = np.arange(15)
# desired --> array([ 0,  1,  2, ..., 12, 13, 14])
np.set_printoptions(threshold=6)    #Limit the number of items printed in python numpy array a to a maximum of 6 elements.
print(a)

[ 0  1  2 ... 12 13 14]


In [26]:
#24. How to print the full numpy array without truncating it?
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)
np.set_printoptions(threshold=sys.maxsize)
#np.set_printoptions(threshold=np.nan)
print(a)


[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [27]:
#25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=",", dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]


In [29]:
#26. How to extract a particular column from 1D array of tuples?
species = np.array([row[4] for row in iris])
print(species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


In [33]:
#27. How to convert a 1d array of tuples to a 2d numpy array?

#method-1
iris_2d = np.array([row[:4] for row in iris])
print(iris_2d[:5])
# Method 2: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris])
print(iris_2d[:5])
# Alt Method 2: Import only the first 4 columns from source url
iris_2d=np.genfromtxt(url, delimiter=',', dtype='object', usecols=[0,1,2,3])
print(iris_2d[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2']
 [b'4.9' b'3.0' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.3' b'0.2']
 [b'4.6' b'3.1' b'1.5' b'0.2']
 [b'5.0' b'3.6' b'1.4' b'0.2']]
[[b'5.1' b'3.5' b'1.4' b'0.2']
 [b'4.9' b'3.0' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.3' b'0.2']
 [b'4.6' b'3.1' b'1.5' b'0.2']
 [b'5.0' b'3.6' b'1.4' b'0.2']]
[[b'5.1' b'3.5' b'1.4' b'0.2']
 [b'4.9' b'3.0' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.3' b'0.2']
 [b'4.6' b'3.1' b'1.5' b'0.2']
 [b'5.0' b'3.6' b'1.4' b'0.2']]


In [48]:
#28. How to compute the mean, median, standard deviation of a numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=",", dtype='object')
sepallength_list = np.array([row[:1] for row in iris], dtype='float')
mean = np.mean(sepallength_list)
meadin =np.median(sepallength_list)
sd = np.std(sepallength_list)
print(mean, meadin, sd)

5.843333333333334 5.8 0.8253012917851409


In [52]:
#29. How to normalize an array so the values range exactly between 0 and 1?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

max=sepallength_list.max()
min=sepallength_list.min()
#method-1
s= (sepallength - min) / (max - min)
#Method-2: .ptp()
s=(sepallength - min)/np.ptp(sepallength_list)
print(s)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

In [55]:
#30. How to compute the softmax score?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
softmax_score = np.exp(sepallength-np.max(sepallength))/np.sum(np.exp(sepallength-np.max(sepallength)))
print(softmax_score)

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

In [63]:
#31. How to find the percentile scores of a numpy array?
##Q. Find the 5th and 95th percentile of iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

percentile_fifth = np.percentile(sepallength, 5)
percentile_Nintyfive = np.percentile(sepallength, 95)

print(percentile_fifth)
print(percentile_Nintyfive)
print(np.percentile(sepallength, q=[5, 95]))

4.6
7.254999999999998
[4.6   7.255]


In [73]:
#32. How to insert values at random positions in an array?
#Q. Insert np.nan values at 20 random positions in iris_2d dataset
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
np.random.seed(10)
indices= np.random.choice(len(iris_2d), size=20, replace=False)
iris_2d[indices]=np.nan
print(iris_2d)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [nan nan nan nan nan]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [nan nan nan nan nan]
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [nan nan nan nan nan]
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [nan nan nan nan nan]
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.3' b'1.7' b'0.5' b'Ir

In [83]:
#33. How to find the position of missing values in numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
np.random.seed(10)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
sepallength= np.array([row.tolist()[:1] for row in iris_2d])
print(np.isnan(sepallength).sum())
print(np.where(np.isnan(sepallength)))

4
(array([ 15,  62, 125, 139], dtype=int64), array([0, 0, 0, 0], dtype=int64))


In [ ]:
#34. How to filter a numpy array based on two or more conditions?
